### ISSUE TITLE
Invalid Hook Call issue

### ISSUE THREAD

**Issue by roecc** [yuzhva/react-leaflet-markercluster#190] opened 2022-05-15 12:38 UTC
In a fresh project with nothing but newest version of react, leaflet etc. installed, the app breaks as soon as i try to implement MarkerClusterGroup throwing me a "Invalid Hook Call" issue. I might be doing something wrong, but i can't find the problem.

**Comment by barbalex** [comment] 2022-05-23 16:39
duplicate of https://github.com/yuzhva/react-leaflet-markercluster/issues/187

**Closed** 2022-07-10 04:15 UTC
Labels: wontfix
