### ISSUE TITLE
Error from node modules in style.min.css, 

### ISSUE THREAD

**Issue by vasukumar169** [YUzhva/react-leaflet-markercluster#32] opened 2017-07-24 04:44 UTC
Hi I am getting below errors when using the components for the same.

Error 1 - a : Module parse failed: /home/vasu/Documents/iRoute/iRouteReact/node_modules/react-leaflet-markercluster/dist/style.min.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

Error 1 - b : /~/react-leaflet-markercluster/dist/style.min.css
Module parse failed: /home/vasu/Documents/iRoute/iRouteReact/node_modules/react-leaflet-markercluster/dist/style.min.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.

Please, let me know what configurations are to be changed

I am attaching my copy of code.

[index (copy).txt](https://github.com/YUzhva/react-leaflet-markercluster/files/1168819/index.copy.txt)

**Comment by YUzhva** [comment] 2017-07-24 06:54
Related to issue #28 

The issue is raised because at this plugin we are importing `styles.css` inside component, so you need to add .css loader to your application.

Are you using webpack?

**Comment by vasukumar169** [comment] 2017-07-24 13:00
Yes I am using webpack.

**Comment by lukeshumard** [comment] 2017-10-12 14:05
Is there a way for this to work without using a CSS loader?

**Comment by YUzhva** [comment] 2017-10-12 14:18
@lukeshumard Unfortunate no.

That issue will be fixed in v1.2.0

**Comment by YUzhva** [comment] 2017-10-16 12:32
P.S: I decided to combine all the issues that touch to that refactoring into issue #48

**Closed by YUzhva** 2017-10-16 12:32 UTC
Labels: bug, enhancement
